# uninstall.yml - Remove reader-sync from this machine
#
# Unloads launchd, removes plist, deletes repo.
# Fails if uncommitted changes exist.
#
# Usage:
#   ansible-playbook uninstall.yml

---
- name: Uninstall reader-sync
  hosts: localhost
  connection: local
  gather_facts: yes

  pre_tasks:
    - name: Verify macOS
      ansible.builtin.fail:
        msg: "reader-sync only supports macOS"
      when: ansible_system != "Darwin"

    - name: Load default configuration
      ansible.builtin.include_vars:
        file: vars/default.yml

    - name: Load platform-specific configuration
      ansible.builtin.include_vars:
        file: vars/platform/darwin.yml

  tasks:
    - name: Check if repo exists
      ansible.builtin.stat:
        path: "{{ install_path }}/.git"
      register: repo_stat

    - name: Nothing to uninstall
      ansible.builtin.debug:
        msg: "No installation found at {{ install_path }}"
      when: not repo_stat.stat.exists

    - name: End if no repo
      ansible.builtin.meta: end_play
      when: not repo_stat.stat.exists

    - name: Check for uncommitted changes
      ansible.builtin.command: git status --porcelain
      args:
        chdir: "{{ install_path }}"
      register: git_status
      changed_when: false

    - name: Fail if uncommitted changes
      ansible.builtin.fail:
        msg: |
          
          ═══════════════════════════════════════════════════════════
          ⚠️  Cannot uninstall: uncommitted changes detected
          ═══════════════════════════════════════════════════════════
          
          Commit or stash your changes first:
            cd {{ install_path }}
            git status
            git stash  # or git commit
          
          ═══════════════════════════════════════════════════════════
      when: git_status.stdout | length > 0

    # =========================================================================
    # Unload launchd
    # =========================================================================

    - name: Check if launchd plist exists
      ansible.builtin.stat:
        path: "{{ launchd_plist_path }}"
      register: plist_stat

    - name: Check if launchd job is loaded
      ansible.builtin.command: launchctl list
      register: launchctl_list
      changed_when: false
      when: plist_stat.stat.exists

    - name: Unload launchd job
      ansible.builtin.command: launchctl unload {{ launchd_plist_path }}
      when:
        - plist_stat.stat.exists
        - launchd_label in launchctl_list.stdout
      changed_when: true
      failed_when: false

    - name: Remove launchd plist
      ansible.builtin.file:
        path: "{{ launchd_plist_path }}"
        state: absent

    # =========================================================================
    # Remove Repository
    # =========================================================================

    - name: Remove repository
      ansible.builtin.file:
        path: "{{ install_path }}"
        state: absent

    - name: Uninstall complete
      ansible.builtin.debug:
        msg: |
          
          ═══════════════════════════════════════════════════════════
          ✅ reader-sync uninstalled
          ═══════════════════════════════════════════════════════════
          
          Removed: {{ install_path }}
          Removed: {{ launchd_plist_path }}
          
          To reinstall:
            ansible-playbook install.yml
          
          ═══════════════════════════════════════════════════════════
