# vars/default.yml - Default configuration for reader-sync
#
# Override with: ansible-playbook install.yml -e "variable=value"

---
# Git repository
git_repo: "git@github.com:mrjamfhi/reader-sync.git"
git_branch: "main"

# Installation path
install_path: "{{ ansible_env.HOME }}/repos/reader-sync"

# Environment-specific API URLs
prod_api_url: "http://synology:8000"
dev_api_url: "http://localhost:8000"

# Environment-specific paths
prod_input_dir: "/Volumes/data/prod/input"
prod_newspaper_dir: "/Volumes/data/prod/publications"
dev_input_dir: "{{ install_path }}/../worker-celery/input"
dev_newspaper_dir: "{{ install_path }}/../worker-celery/data/dev/publications"

# SMB share configuration (for auto-mounting network shares)
smb_enabled: true
smb_share_url: "smb://synology/data"
smb_mount_point: "/Volumes/data"

# Sync behavior
poll_interval: 2
poll_timeout: 900
auto_eject: true

# launchd configuration
launchd_label: "com.reader-sync"
