# vars/default.yml - Default configuration for reader-sync pod
#
# These are sensible defaults for standalone use.
# In a GitOps setup, these values are overridden by vm-manager:
#
#   vm-manager/
#   └── group_vars/
#       ├── all.yml         ← Global overrides (smb_share_url, etc.)
#       └── macbook.yml     ← Host-specific overrides
#
# Override via command line:
#   ansible-playbook install.yml -e "prod_api_url=http://192.168.1.100:8000"

---
# =============================================================================
# Deployment Configuration
# =============================================================================
# These control WHERE and HOW reader-sync is installed.

# Git repository
git_repo: "git@github.com:mrjamfhi/reader-sync.git"
git_branch: "main"

# Derived from playbook location: repos/pod-reader-sync → repos/reader-sync
repos_base: "{{ playbook_dir | dirname }}"
install_path: "{{ repos_base }}/reader-sync"

# launchd service label
launchd_label: "com.reader-sync"

# =============================================================================
# Application Configuration
# =============================================================================
# These are templated into config.json for the reader-sync application.
# In GitOps, these come from vm-manager group_vars.

# Environment-specific API URLs
prod_api_url: "http://cerere.jamfhi.com:8000"
dev_api_url: "http://localhost:8000"

# Environment-specific paths
prod_input_dir: "/Volumes/data/prod/input"
prod_newspaper_dir: "/Volumes/data/prod/publications"
dev_input_dir: "{{ repos_base }}/worker-celery/input"
dev_newspaper_dir: "{{ repos_base }}/worker-celery/data/dev/publications"

# SMB share configuration (for auto-mounting network shares on macOS)
smb_enabled: true
smb_share_url: "smb://synology/data"
smb_mount_point: "/Volumes/data"

# Sync behavior
poll_interval: 2
poll_timeout: 900
auto_eject: true
